### PR TITLE
Fix some JS warnings and imgur wizard for cinnamon 3.4

### LINKED ISSUE #74: some JS warning
I see some JS warnings in `xsession-errors`:

```
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js 433]: reference to undefined property this._uuid
```
and
```
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 398]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 399]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 400]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 401]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/screenshot.js 1109]: reference to undefined property event.get_source(...).style_class
Cjs-Message: JS WARNING: [~/.local/share/cinnamon/applets/capture@rjanja/3.2/applet.js 1306]: Too many arguments to method St.TextureCache.load_uri_sync: expected 4, got 5

```

### LINKED ISSUE #75: Imgur integration wizard doesn't work in Mint 18.2
Updated to Mint 18.2 from 18.1 and applet stopped working, after reset can't link imgur account, nothing happens after clicking "Wizard: Connect to your account..." button. Other functionality and anonymous uploading seems to work well.
Cinnamon version is 3.4.6
Applet version is 1.14
screenshot-area-2017-09-04-120615

### PR DESCRIPTION
**Pull request by NikoKrause**
The first commit removes some trailing spaces (I use atom, which removes them automatically. To make review easier I put this into a separate commit).

The second commit fixes some JS warnings. Closes #74 

The third commit fixes #75 
In Cinnamon 3.4 the [CJS Javascript interpreter was rebased and now runs on mozjs 38.](https://www.linuxmint.com/rel_sonya_cinnamon_whatsnew.php) It causes js to crash, if a variable is declared twice within the same scope. Removing those duplicate `let` declarations and the wizard starts as expected.

And the `res` variable was undeclared.

### CODE REVIEW

**Comment by rjanja** [comment]
Thanks @NikoKrause! Sorry it took me so long to take a look at this PR. Cheers!
